#!/bin/sh

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 PROJECTNAME IP"
  exit 1
fi

pname="$1"
ip="$2"

sed -e "s/%IP%/$ip/g" -e "s/%PNAME%/$pname/g" /usr/local/etc/nginx_tl_template.conf > /etc/nginx/conf.d/${pname}.conf

/sbin/service nginx reload >/dev/null 2>/dev/null
