#!/bin/sh
source /root/.keystonerc

image="$1"

case "$image" in compute)
  machine=project-computenode
  ;;
  login)
  machine=project-loginnode
  ;;
  service)
  machine=topolino-q
  ;;
  *)
  echo "Usage: $0 IMAGE "
  echo
  echo "Where IMAGE is one of compute, login and service."
  exit 1
  ;;
esac

currentid=`glance image-show "$machine"  | tr -d ' '| grep '|id|' | cut -d'|' -f 3`
oldid=`glance image-show "${machine}-stable"  | tr -d ' '| grep '|id|' | cut -d'|' -f 3`

if [ -z "$currentid" ]; then
  echo "No image to approve? Pherhaps you need to refreshimage and verify."
  exit 1
fi


glance image-update --name "${machine}-stable" "$currentid" || exit 1

if [ -n "$oldid" ]; then 
  glance image-delete "$oldid"
fi


