#!/bin/sh

mkdir -p /tmp/.passwd_line_cache
f="/tmp/.passwd_line_cache/$1"

if find "$f"  -mtime -1 2>/dev/null |  fgrep -q "$f" ; then
  # We have a cached value?
  cat "$f"
  exit
else 
  # No cache or old? Update and store
  ssh root@ldap passwd_line "$1" > "$f.new.$$"
  if test -s "$f.new.$$" ; then
   mv "$f.new.$$" "$f"
   cat "$f"
   exit
  else
     ssh root@ldap passwd_line "$1" 
  fi
fi

