#!/bin/sh
source /root/.keystonerc

image="$1"

case "$image" in compute)
  source=/dev/vg_tsn/project-computenode.mosler.uppmax.uu.se-disk1
  machine=project-computenode
  ;;
  login)
  source=/dev/vg_tsn/project-loginnode.mosler.uppmax.uu.se-disk1
  machine=project-loginnode
  ;;
  service)
  source=/var/lib/libvirt/images/topolino-q.mosler.uppmax.uu.se-disk1
  machine=topolino-q
  ;;
  *)
  echo "Usage: $0 IMAGE "
  echo
  echo "Where IMAGE is one of compute, login and service."
  exit 1
  ;;
esac

tname="/tmp/$machine.$$"

if virsh list | grep -q "$machine"; then
  echo "Hrrm, $machine seems to be running, please verify that it's shut down properly."
  exit 1
fi

#qemu-img create   -f qcow2 "${tname}.large" 2T
#virt-resize --output-format qcow2 --no-expand-content --expand /dev/sda3 "$source" "${tname}.large"

echo Compressing image.
qemu-img convert -p -O qcow2 -c "$source" "$tname"
#qemu-img convert -O qcow2 -c "${tname}.large" "${tname}"
#rm -f "${tname}.large"


virsh start "${machine}.mosler.uppmax.uu.se"


virt-sysprep --enable udev-persistent-net,abrt-data,bash-history,crash-data,dhcp-client-state,logfiles,machine-id,mail-spool,net-hwaddr,pacct-log,package-manager-cache,puppet-data-log,random-seed,rpm-db,utmp,yum-uuid -a "$tname" 


md=`md5sum "$tname" | cut -f 1 -d ' '`
size=`stat -c %s "$tname" `

currentid=`glance image-show "$machine"  | tr -d ' '| grep '|id|' | cut -d'|' -f 3`

echo Uploading new image

glance image-create --file "$tname" --disk-format qcow2 --container-format bare --checksum "$md" --size "$size" --name "$machine" --is-public True --progress && if [ -n "$currentid" ]; then glance image-delete "$currentid"; fi

rm -f "$tname" 
