#!/bin/sh

KEYSTONETHREE=https://172.27.0.32:5000/v3

if [ "$#" -ne 2 ]; then
  exit 1
fi

token="$1"
username="$2"

curl -s -H "Content-Type: application/json"  -d '{"auth":{"identity":{"methods": ["token"],"token":{"id": "'$token'"}}}}' "$KEYSTONETHREE/auth/tokens" | jq -r .token.user.name | grep -q "^$username\$" || exit 1

exit 0


