#!/bin/sh

KEYSTONETHREE=https://172.27.0.32:5000/v3
KEYSTONETWO=https://172.27.0.32:5000/v2.0

token="`echo $QUERY_STRING | sed -ne 's/.*token=\([^&]*\)\&*.*/\1/p'`"
new="`echo $QUERY_STRING | sed -ne 's/.*set=\([^&]*\)\&*.*/\1/p'`"

username=`curl -s -H "Content-Type: application/json"  -d '{"auth":{"identity":{"methods": ["token"],"token":{"id": "'$token'"}}}}' "$KEYSTONETHREE/auth/tokens" | jq -r .token.user.name`

if [ "x$new" = x ]; then
  :
else
  # We want to set a new project, verify access.
 if curl -s -H "X-Auth-Token: $token" "$KEYSTONETWO/tenants" | jq -r .tenants[].name | grep -q ^"$new"'$'; then
   :
  else

    echo 'Status: 401 Unauthorized'
    echo
    echo "No access to project $new!"
    exit 1
  fi


  if grep -q ^"$new": /usr/local/etc/tlprojects; then
    :
  else
     echo 'Status: 500 Internal server error'
     echo
     echo "Unkown project $new "
     exit 1
   fi


  if grep -q ^"$new"'$'  "/var/lib/tl-director/$username" 2>/dev/null;  then
    :
  else
    # Change of project
    echo "$new" > "/var/lib/tl-director/$username"

    while [ "/var/lib/tl-director/$username" -nt /opt/thinlinc/etc/conf.d/vsmserver.hconf ]; do
      sleep 1;
    done
  fi
fi

current=""

if [ -f "/var/lib/tl-director/$username" ]; then
  current=`cat "/var/lib/tl-director/$username"`
fi


echo 'Status: 200 OK'
echo
echo '{"project": "'"$current"'"}'

