#!/bin/sh


for p in passwd group; do
  if [ -r "/meles/import/etc/$p" -a "/meles/import/etc/$p" -nt "/etc/$p" ]; then
    cat "/meles/import/etc/$p" /etc/"$p" | sed -e 's,:/home/,:/meles/import/home/,' |  sort -u -t: -k 1 | sort -t':' -k 3,3 -n > /etc/"${p}.new"
    mv /etc/"${p}.new" /etc/"$p" 
  fi
done


