#!/bin/sh

PATH=$PATH:/sbin:/usr/sbin

myuid=`id -u`

if [ "$myuid" -eq 0 ]; then
  :
else
  echo "Please run as root/sudo"
  exit 1
fi

source /root/.keystonerc

check_and_make_tokenadmin () {

  if keystone  user-role-list --user="$1" --tenant=bils_tokenadmins | grep -q tokenadmin ; then
    :
  else
    keystone  user-role-add --user="$1" --tenant=bils_tokenadmins --role="tokenadmin"  >/dev/null
  fi

}


for p in `cat /etc/mosler/bils_tokenadmins`; do
  check_and_make_tokenadmin "$p"
done

keystone user-list | fgrep '@' | while read a username c; do 

  if grep -q "$username" /etc/mosler/bils_tokenadmins; then
    :
  else
    # User not tokenadmin, verify
    if  keystone  user-role-list --user="$username" --tenant=bils_tokenadmins | grep -q tokenadmin ; then
       keystone  user-role-delete --user="$username" --tenant=bils_tokenadmins --role="tokenadmin"
    fi    
  fi
done

