#!/bin/sh

/usr/local/sbin/project_ips | while read pname ip; do
 
 ssh root@thinlinc-master /usr/local/sbin/mapproj "$pname" "$ip" </dev/null
 ssh root@tos1  /usr/local/sbin/map_thinlinc_nginx "$pname" "$ip" </dev/null

 /usr/local/sbin/project_members "$pname" | while read uname; do 
   ssh root@thinlinc-master /usr/local/sbin/establish_user "$uname" </dev/null
 done 
done
